# Generated by Django 3.2.5 on 2022-02-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='ranking',
        ),
        migrations.AddField(
            model_name='jogador',
            name='pontuacao',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Pontuação'),
        ),
    ]
